#define INST_ADDR_START            0x00000000
#define THREAD_MODE_STACK_START    0x00004000
#define HANDLER_MODE_STACK_START   0x00008000
#define GLOBAL_ADDR_START          0x00110000
#define DALLOC_ADDR_START          0x00120000

#define INST_MEM_SIZE             (THREAD_MODE_STACK_START - INST_ADDR_START)
#define THREAD_MODE_STACK_SIZE    (HANDLER_MODE_STACK_START - THREAD_MODE_STACK_START)
#define HANDLER_MODE_STACK_SIZE   (GLOBAL_ADDR_START - HANDLER_MODE_STACK_START)
#define GLOBAL_ADDR_STACK_SIZE    (DALLOC_ADDR_START - GLOBAL_ADDR_START)
#define DALLOC_MEM_SIZE           (128 * 1024)

#define THREAD_MODE_STACK_TOP     (THREAD_MODE_STACK_START + THREAD_MODE_STACK_SIZE - 4)
#define HANDLER_MODE_STACK_TOP    (HANDLER_MODE_STACK_START + HANDLER_MODE_STACK_SIZE - 4)