#define INST_ADDR_START 0
#define USRSYS_STACK_START 0x00002000
#define SVC_STACK_START    0x00004000
#define IRQ_STACK_START    0x00006000
#define FIQ_STACK_START    0x00007000
#define ABT_STACK_START    0x00008000
#define UND_STACK_START    0x00009000
#define TASK_STACK_START   0x00010000
#define GLOBAL_ADDR_START  0x00110000
#define DALLOC_ADDR_START  0x00120000

#define INST_MEM_SIZE     (USRSYS_STACK_START - INST_ADDR_START)
#define USRSYS_STACK_SIZE (SVC_STACK_START - USRSYS_STACK_START)
#define SVC_STACK_SIZE    (IRQ_STACK_START - SVC_STACK_START)
#define IRQ_STACK_SIZE    (FIQ_STACK_START - IRQ_STACK_START)
#define FIQ_STACK_SIZE    (ABT_STACK_START - FIQ_STACK_START)
#define ABT_STACK_SIZE    (UND_STACK_START - ABT_STACK_START)
#define UND_STACK_SIZE    (TASK_STACK_START - UND_STACK_START)
#define TASK_STACK_SIZE   (GLOBAL_ADDR_START - TASK_STACK_START)
#define DALLOC_MEM_SIZE   (128 * 1024)

#define USRSYS_STACK_TOP (USRSYS_STACK_START + USRSYS_STACK_SIZE - 4)
#define SVC_STACK_TOP    (SVC_STACK_START + SVC_STACK_SIZE - 4)
#define IRQ_STACK_TOP    (IRQ_STACK_START + IRQ_STACK_SIZE - 4)
#define FIQ_STACK_TOP    (FIQ_STACK_START + FIQ_STACK_SIZE - 4)
#define ABT_STACK_TOP    (ABT_STACK_START + ABT_STACK_SIZE - 4)
#define UND_STACK_TOP    (UND_STACK_START + UND_STACK_SIZE - 4)
